# typed: false
# frozen_string_literal: true

# Generated by script/homebrew-formula in tomtom87/Portage — do not
# hand-edit. Re-run that script after releasing portage-cli or any bundled
# adapter/webmcp/decision gem.
class Portage < Formula
  desc "One CLI command to buy from any store, native UCP or not"
  homepage "https://github.com/tomtom87/Portage"
  url "https://rubygems.org/gems/portage-cli-0.13.1.gem"
  sha256 "f6e928f148c60da604dd722ba78f069da38791685d9f2bf89c10cb0b8517673c"
  license "MIT"

  depends_on "ruby"

  resource "base64" do
    url "https://rubygems.org/gems/base64-0.3.0.gem"
    sha256 "27337aeabad6ffae05c265c450490628ef3ebd4b67be58257393227588f5a97b"
  end

  resource "bigdecimal" do
    url "https://rubygems.org/gems/bigdecimal-4.1.3.gem"
    sha256 "61ebe1e5e559bdc3cc6f2c0ee7f427321fc838f59611c294356eb04d6e21cf66"
  end

  resource "erb" do
    url "https://rubygems.org/gems/erb-6.0.7.gem"
    sha256 "c5ca6dc25b0ef974a44dc8f59fe847577122483b1968a38dec305c60bf91ee92"
  end

  resource "faraday" do
    url "https://rubygems.org/gems/faraday-2.14.4.gem"
    sha256 "9bb4408c44621b0dbaaaa39e5dbfc4dbe58cc6751b6eb94d16ae9e1f2f2fab6e"
  end

  resource "faraday-net_http" do
    url "https://rubygems.org/gems/faraday-net_http-3.4.4.gem"
    sha256 "0e78af151747ed1b00f33e25973b4bc220d7f16c00c39676817c8b12331eb588"
  end

  resource "hana" do
    url "https://rubygems.org/gems/hana-1.3.7.gem"
    sha256 "5425db42d651fea08859811c29d20446f16af196308162894db208cac5ce9b0d"
  end

  resource "io-console" do
    url "https://rubygems.org/gems/io-console-0.9.4.gem"
    sha256 "a403304f32928ee85e56d457b4612ca43f2703b561a3258844992bd24085fbb1"
  end

  resource "irb" do
    url "https://rubygems.org/gems/irb-1.18.0.gem"
    sha256 "de9454a0703a54704b9811a5ef31a60c86949fbf4013fcf244fabc7c775248e3"
  end

  resource "jar-dependencies" do
    url "https://rubygems.org/gems/jar-dependencies-0.5.7.gem"
    sha256 "013ce5f4639414ac8cf1169cdbe763da164b81e2d2c983d11042b5ff7bfcce80"
  end

  resource "json" do
    url "https://rubygems.org/gems/json-3.0.2.gem"
    sha256 "8e6d7e7b11384c21230430cef90b71f14849a34a1f4452796670f7c981bd19df"
  end

  resource "json_schemer" do
    url "https://rubygems.org/gems/json_schemer-2.5.0.gem"
    sha256 "2f01fb4cce721a4e08dd068fc2030cffd0702a7f333f1ea2be6e8991f00ae396"
  end

  resource "logger" do
    url "https://rubygems.org/gems/logger-1.7.0.gem"
    sha256 "196edec7cc44b66cfb40f9755ce11b392f21f7967696af15d274dde7edff0203"
  end

  resource "mcp" do
    url "https://rubygems.org/gems/mcp-0.25.0.gem"
    sha256 "8acf3a5f3b60b6fd6e5d9b8ac5eb85ac504766976cbadaca182d2ffe7d795d98"
  end

  resource "mini_portile2" do
    url "https://rubygems.org/gems/mini_portile2-2.8.9.gem"
    sha256 "0cd7c7f824e010c072e33f68bc02d85a00aeb6fce05bb4819c03dfd3c140c289"
  end

  resource "net-http" do
    url "https://rubygems.org/gems/net-http-0.9.1.gem"
    sha256 "25ba0b67c63e89df626ed8fac771d0ad24ad151a858af2cc8e6a716ca4336996"
  end

  resource "portage-ucp" do
    url "https://rubygems.org/gems/portage-ucp-0.13.0.gem"
    sha256 "3a0e6da80c895e1d1892074457fa48fd13dc2909826155be1e76bd3c9c44a48e"
  end

  resource "portage-ucp-bigcommerce" do
    url "https://rubygems.org/gems/portage-ucp-bigcommerce-0.2.1.gem"
    sha256 "0868bf0949c2ba09df0331dd22068687afdebc2fb65755fdfb9e9789158192b7"
  end

  resource "portage-ucp-client" do
    url "https://rubygems.org/gems/portage-ucp-client-0.6.3.gem"
    sha256 "634f8e0459d5c3ae19798078f00b8790ea67d7aafaaae9c16c084ce363a1edab"
  end

  resource "portage-ucp-decision" do
    url "https://rubygems.org/gems/portage-ucp-decision-0.1.2.gem"
    sha256 "e0d93c97d847635dc5678febeebf90031b401d22b54f661f3a3fa027eb5a85f4"
  end

  resource "portage-ucp-etsy" do
    url "https://rubygems.org/gems/portage-ucp-etsy-0.1.5.gem"
    sha256 "6e733f55144c7d70218c1d23921841133e1ada235ae5ac4260f651e821ae02e7"
  end

  resource "portage-ucp-instagram" do
    url "https://rubygems.org/gems/portage-ucp-instagram-0.2.0.gem"
    sha256 "3d5f890f4f4b216d0e21b6776ccbfe450f12c80993cf9b7951714204e6f9e41d"
  end

  resource "portage-ucp-journal" do
    url "https://rubygems.org/gems/portage-ucp-journal-0.1.1.gem"
    sha256 "9e59ac619beb38012bcf92592da333af2ea9a472c2e497467bfc559f58be78ac"
  end

  resource "portage-ucp-magento" do
    url "https://rubygems.org/gems/portage-ucp-magento-0.2.1.gem"
    sha256 "c118171e6be1e344c74e85a14a9802799bdf1ad6125b15e1864a866191a9086d"
  end

  resource "portage-ucp-shopify" do
    url "https://rubygems.org/gems/portage-ucp-shopify-0.6.1.gem"
    sha256 "42056c08c34613869fb77c17f3a1cfad7d65c48a35ac8e9f2ebd965feb437f60"
  end

  resource "portage-ucp-webmcp" do
    url "https://rubygems.org/gems/portage-ucp-webmcp-0.2.0.gem"
    sha256 "9c86aa43ddd2bfcf9276691d2b0a85c28b58189b73bb5766bc8b13ab1aaf43b7"
  end

  resource "portage-ucp-wix" do
    url "https://rubygems.org/gems/portage-ucp-wix-0.2.1.gem"
    sha256 "c2244c632eaf2e155d1cb9a1beabf84f42b069daa64d04a50340d8e0cbc8b754"
  end

  resource "portage-ucp-woocommerce" do
    url "https://rubygems.org/gems/portage-ucp-woocommerce-0.3.0.gem"
    sha256 "895a3b24170e68f7275c4765501a0530caac78910bd75f5611361f393c927955"
  end

  resource "pp" do
    url "https://rubygems.org/gems/pp-0.6.4.gem"
    sha256 "dfcb0fce700c41456265922884f9fe195d7fbb0674a3578e6c0f69588e82b570"
  end

  resource "prettyprint" do
    url "https://rubygems.org/gems/prettyprint-0.2.0.gem"
    sha256 "2bc9e15581a94742064a3cc8b0fb9d45aae3d03a1baa6ef80922627a0766f193"
  end

  resource "prism" do
    url "https://rubygems.org/gems/prism-1.9.0.gem"
    sha256 "7b530c6a9f92c24300014919c9dcbc055bf4cdf51ec30aed099b06cd6674ef85"
  end

  resource "rack" do
    url "https://rubygems.org/gems/rack-3.2.7.gem"
    sha256 "93e13e1c24f93556671d85d2d79fa228c3485815c50d7e2f265b5330c6528fb7"
  end

  resource "rbs" do
    url "https://rubygems.org/gems/rbs-4.2.0.gem"
    sha256 "51f7b886dcc05bc09e10b901daa6a81829f6adc03101d6ca9ea4aac6103e0674"
  end

  resource "rdoc" do
    url "https://rubygems.org/gems/rdoc-8.1.0.gem"
    sha256 "befc37880a5cfd36dcb176c748b5fd5ee39dd3536a75e81824e4972ce230f60a"
  end

  resource "regexp_parser" do
    url "https://rubygems.org/gems/regexp_parser-2.13.1.gem"
    sha256 "5aedb6b7c35688f51e86eef17a15374dfd287c83f4ca644b2c5f3ec50a33b44b"
  end

  resource "reline" do
    url "https://rubygems.org/gems/reline-0.7.0.gem"
    sha256 "5b012d8e55dbf9d450f12bde2cf7d15ff546ae80b3f8f3b30e570d431815583d"
  end

  resource "simpleidn" do
    url "https://rubygems.org/gems/simpleidn-0.3.0.gem"
    sha256 "12ca730bed2f3db04d11e9bfd1bca3e11fb37f55b21eb2e9793fb5814bf54d03"
  end

  resource "sqlite3" do
    url "https://rubygems.org/gems/sqlite3-2.9.6.gem"
    sha256 "956fe606956420d04ac7157d3ace620c8caba2135b2e05c76e483493da24d08e"
  end

  resource "tsort" do
    url "https://rubygems.org/gems/tsort-0.2.0.gem"
    sha256 "9650a793f6859a43b6641671278f79cfead60ac714148aabe4e3f0060480089f"
  end

  resource "uri" do
    url "https://rubygems.org/gems/uri-1.1.1.gem"
    sha256 "379fa58d27ffb1387eaada68c749d1426738bd0f654d812fcc07e7568f5c57c6"
  end

  def install
    ENV["GEM_HOME"] = libexec
    ENV["GEM_PATH"] = libexec

    resources.each do |r|
      r.stage do
        system "gem", "install", Dir["*.gem"].first,
               "--install-dir", libexec, "--no-document", "--ignore-dependencies"
      end
    end

    system "gem", "install", cached_download,
           "--install-dir", libexec, "--no-document", "--ignore-dependencies"

    bin.install libexec/"bin/portage"
    bin.install libexec/"bin/portage-console"
    bin.env_script_all_files(libexec/"bin", GEM_HOME: libexec, GEM_PATH: libexec)
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/portage --version").strip

    # `doctor` is offline and loads portage-cli plus every bundled adapter, so
    # it checks the whole install without a store or network fixture. Its
    # exit code depends on the user's setup (a fresh HOME has no shipping
    # address, so it warns), so this checks the report instead: the keg is
    # detected as a Homebrew install and every bundled adapter loads.
    # Doctor's messages aren't ASCII; pipe_output's string takes the locale's
    # encoding, which isn't UTF-8 in every test environment.
    findings = JSON.parse(pipe_output("#{bin}/portage doctor --json").dup.force_encoding("UTF-8"))
    install = findings.find { |f| f["check"] == "install" }
    assert_equal "homebrew", install.dig("details", "method")
    adapters = findings.find { |f| f["check"] == "adapters" }
    assert_equal "info", adapters["level"], adapters["message"]
  end
end
