# typed: false
# frozen_string_literal: true

# Generated by script/homebrew-formula in tomtom87/Portage — do not
# hand-edit. Re-run that script after releasing portage-cli or any bundled
# adapter/webmcp/decision gem.
class Portage < Formula
  desc "One CLI command to buy from any store, native UCP or not"
  homepage "https://github.com/tomtom87/Portage"
  url "https://rubygems.org/gems/portage-cli-0.7.3.gem"
  sha256 "0dc8c887097f97f8fb018b544f0fa1c7febefd8a4f10d6bffa81f134d1b0b1cc"
  license "MIT"

  depends_on "ruby"

  resource "base64" do
    url "https://rubygems.org/gems/base64-0.3.0.gem"
    sha256 "27337aeabad6ffae05c265c450490628ef3ebd4b67be58257393227588f5a97b"
  end

  resource "bigdecimal" do
    url "https://rubygems.org/gems/bigdecimal-4.1.3.gem"
    sha256 "61ebe1e5e559bdc3cc6f2c0ee7f427321fc838f59611c294356eb04d6e21cf66"
  end

  resource "erb" do
    url "https://rubygems.org/gems/erb-6.0.7.gem"
    sha256 "c5ca6dc25b0ef974a44dc8f59fe847577122483b1968a38dec305c60bf91ee92"
  end

  resource "faraday" do
    url "https://rubygems.org/gems/faraday-2.14.4.gem"
    sha256 "9bb4408c44621b0dbaaaa39e5dbfc4dbe58cc6751b6eb94d16ae9e1f2f2fab6e"
  end

  resource "faraday-net_http" do
    url "https://rubygems.org/gems/faraday-net_http-3.4.4.gem"
    sha256 "0e78af151747ed1b00f33e25973b4bc220d7f16c00c39676817c8b12331eb588"
  end

  resource "hana" do
    url "https://rubygems.org/gems/hana-1.3.7.gem"
    sha256 "5425db42d651fea08859811c29d20446f16af196308162894db208cac5ce9b0d"
  end

  resource "io-console" do
    url "https://rubygems.org/gems/io-console-0.9.4.gem"
    sha256 "a403304f32928ee85e56d457b4612ca43f2703b561a3258844992bd24085fbb1"
  end

  resource "irb" do
    url "https://rubygems.org/gems/irb-1.18.0.gem"
    sha256 "de9454a0703a54704b9811a5ef31a60c86949fbf4013fcf244fabc7c775248e3"
  end

  resource "jar-dependencies" do
    url "https://rubygems.org/gems/jar-dependencies-0.5.7.gem"
    sha256 "013ce5f4639414ac8cf1169cdbe763da164b81e2d2c983d11042b5ff7bfcce80"
  end

  resource "json" do
    url "https://rubygems.org/gems/json-3.0.2.gem"
    sha256 "8e6d7e7b11384c21230430cef90b71f14849a34a1f4452796670f7c981bd19df"
  end

  resource "json_schemer" do
    url "https://rubygems.org/gems/json_schemer-2.5.0.gem"
    sha256 "2f01fb4cce721a4e08dd068fc2030cffd0702a7f333f1ea2be6e8991f00ae396"
  end

  resource "logger" do
    url "https://rubygems.org/gems/logger-1.7.0.gem"
    sha256 "196edec7cc44b66cfb40f9755ce11b392f21f7967696af15d274dde7edff0203"
  end

  resource "mcp" do
    url "https://rubygems.org/gems/mcp-0.25.0.gem"
    sha256 "8acf3a5f3b60b6fd6e5d9b8ac5eb85ac504766976cbadaca182d2ffe7d795d98"
  end

  resource "net-http" do
    url "https://rubygems.org/gems/net-http-0.9.1.gem"
    sha256 "25ba0b67c63e89df626ed8fac771d0ad24ad151a858af2cc8e6a716ca4336996"
  end

  resource "portage-ucp" do
    url "https://rubygems.org/gems/portage-ucp-0.10.0.gem"
    sha256 "efe5bf4c962ad5078c7f46c130893ba4fd003621fc25a876a0ebd705444bad44"
  end

  resource "portage-ucp-bigcommerce" do
    url "https://rubygems.org/gems/portage-ucp-bigcommerce-0.1.4.gem"
    sha256 "9e3b8456b7d86a0eadd9e153dc69c345d765da07c70977b6c7a3dcce6b7acd34"
  end

  resource "portage-ucp-client" do
    url "https://rubygems.org/gems/portage-ucp-client-0.6.3.gem"
    sha256 "634f8e0459d5c3ae19798078f00b8790ea67d7aafaaae9c16c084ce363a1edab"
  end

  resource "portage-ucp-decision" do
    url "https://rubygems.org/gems/portage-ucp-decision-0.1.1.gem"
    sha256 "bbc78f7759dfaf4e7af04d81ce06b9fd62878841faa75da34117530ca8718b00"
  end

  resource "portage-ucp-etsy" do
    url "https://rubygems.org/gems/portage-ucp-etsy-0.1.4.gem"
    sha256 "529384133301fff2059f06ca56c23969bea46a895f58dc543893e66144139392"
  end

  resource "portage-ucp-instagram" do
    url "https://rubygems.org/gems/portage-ucp-instagram-0.1.5.gem"
    sha256 "7aca0dc3beecab98a3947e75be205c878389fcd584956c6508c29e0f6fbf1484"
  end

  resource "portage-ucp-journal" do
    url "https://rubygems.org/gems/portage-ucp-journal-0.1.1.gem"
    sha256 "9e59ac619beb38012bcf92592da333af2ea9a472c2e497467bfc559f58be78ac"
  end

  resource "portage-ucp-magento" do
    url "https://rubygems.org/gems/portage-ucp-magento-0.1.4.gem"
    sha256 "a58804505141d2213f003ae8f21814b89c95e84e9c5cd5f30693a8cf50a8e05f"
  end

  resource "portage-ucp-shopify" do
    url "https://rubygems.org/gems/portage-ucp-shopify-0.5.1.gem"
    sha256 "02368c8e1cf117bdd3a71ddd9a4bd1acc4fd12b1967e318396ae2cbb584855c0"
  end

  resource "portage-ucp-webmcp" do
    url "https://rubygems.org/gems/portage-ucp-webmcp-0.1.1.gem"
    sha256 "0a438fe4523c91391972b206f2b0318302d6b437fde1c18f629cb93bf4a5d390"
  end

  resource "portage-ucp-wix" do
    url "https://rubygems.org/gems/portage-ucp-wix-0.1.4.gem"
    sha256 "16dcc37ff3ec06a6078063792d4e0e875c90e9f2e8401327780c8dc80a079d9f"
  end

  resource "portage-ucp-woocommerce" do
    url "https://rubygems.org/gems/portage-ucp-woocommerce-0.2.1.gem"
    sha256 "3cfd1a5060fc9cc42ccc61e6839ba75ce28146129f73b43e02dd37aaff6abcaa"
  end

  resource "pp" do
    url "https://rubygems.org/gems/pp-0.6.4.gem"
    sha256 "dfcb0fce700c41456265922884f9fe195d7fbb0674a3578e6c0f69588e82b570"
  end

  resource "prettyprint" do
    url "https://rubygems.org/gems/prettyprint-0.2.0.gem"
    sha256 "2bc9e15581a94742064a3cc8b0fb9d45aae3d03a1baa6ef80922627a0766f193"
  end

  resource "prism" do
    url "https://rubygems.org/gems/prism-1.9.0.gem"
    sha256 "7b530c6a9f92c24300014919c9dcbc055bf4cdf51ec30aed099b06cd6674ef85"
  end

  resource "rack" do
    url "https://rubygems.org/gems/rack-3.2.7.gem"
    sha256 "93e13e1c24f93556671d85d2d79fa228c3485815c50d7e2f265b5330c6528fb7"
  end

  resource "rbs" do
    url "https://rubygems.org/gems/rbs-4.2.0.gem"
    sha256 "51f7b886dcc05bc09e10b901daa6a81829f6adc03101d6ca9ea4aac6103e0674"
  end

  resource "rdoc" do
    url "https://rubygems.org/gems/rdoc-8.0.0.gem"
    sha256 "03bf8c08a9639658855a0cfd77c0abca8325c227693f7f33f82957811348c469"
  end

  resource "regexp_parser" do
    url "https://rubygems.org/gems/regexp_parser-2.13.0.gem"
    sha256 "d105d95d2138954e73914d2fbfb3d0a8f8605a49a3e89864c32e78b9107cb770"
  end

  resource "reline" do
    url "https://rubygems.org/gems/reline-0.7.0.gem"
    sha256 "5b012d8e55dbf9d450f12bde2cf7d15ff546ae80b3f8f3b30e570d431815583d"
  end

  resource "simpleidn" do
    url "https://rubygems.org/gems/simpleidn-0.3.0.gem"
    sha256 "12ca730bed2f3db04d11e9bfd1bca3e11fb37f55b21eb2e9793fb5814bf54d03"
  end

  resource "tsort" do
    url "https://rubygems.org/gems/tsort-0.2.0.gem"
    sha256 "9650a793f6859a43b6641671278f79cfead60ac714148aabe4e3f0060480089f"
  end

  resource "uri" do
    url "https://rubygems.org/gems/uri-1.1.1.gem"
    sha256 "379fa58d27ffb1387eaada68c749d1426738bd0f654d812fcc07e7568f5c57c6"
  end

  def install
    ENV["GEM_HOME"] = libexec
    ENV["GEM_PATH"] = libexec

    resources.each do |r|
      r.stage do
        system "gem", "install", Dir["*.gem"].first,
               "--install-dir", libexec, "--no-document", "--ignore-dependencies"
      end
    end

    system "gem", "install", cached_download,
           "--install-dir", libexec, "--no-document", "--ignore-dependencies"

    bin.install libexec/"bin/portage"
    bin.install libexec/"bin/portage-console"
    bin.env_script_all_files(libexec/"bin", GEM_HOME: libexec, GEM_PATH: libexec)
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/portage --version").strip

    # `doctor` never touches the network (it only inspects local
    # Portage::Ucp::Configuration), so this exercises a full offline load
    # of portage-cli plus every bundled gem without a store or network
    # fixture. Findings are non-empty on a freshly installed config (no
    # authenticator/rate_limiter/signing keys set up yet), hence exit 1.
    output = shell_output("#{bin}/portage doctor --json", 1)
    findings = JSON.parse(output)
    assert_kind_of Array, findings
    refute_predicate findings, :empty?
  end
end
